#!/usr/bin/env python3
"""
PostCompact hook: extracts the compaction summary from the transcript
and writes it to ~/.claude/last-compact-summary.md for cross-session recovery.

Security notes:
  - Reads stdin via json.load() — no shell word splitting
  - transcript_path validated as an absolute path before use
  - All file I/O uses Python builtins — no shell execution
  - Output file is user-scoped (~/.claude/) — no privilege escalation
"""
import json
import os
import sys
from datetime import datetime, timezone
from typing import Optional

OUTPUT_PATH = os.path.expanduser("~/.claude/last-compact-summary.md")


def extract_summary(transcript_path: str) -> Optional[str]:
    try:
        with open(transcript_path, "r", encoding="utf-8") as f:
            entries = [json.loads(line) for line in f if line.strip()]
    except (OSError, json.JSONDecodeError):
        return None

    boundary_uuid = None
    for entry in reversed(entries):
        if entry.get("type") == "system" and entry.get("subtype") == "compact_boundary":
            boundary_uuid = entry.get("uuid")
            break

    if not boundary_uuid:
        return None

    for entry in entries:
        if entry.get("parentUuid") == boundary_uuid and entry.get("type") == "user":
            msg = entry.get("message") or entry.get("content")
            if isinstance(msg, dict):
                return msg.get("content", "")
            if isinstance(msg, str):
                return msg
            break

    return None


def main():
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        sys.exit(0)

    raw_path = data.get("transcript_path", "")
    if not raw_path or not os.path.isabs(raw_path):
        sys.exit(0)
    transcript_path = os.path.normpath(raw_path)

    summary = extract_summary(transcript_path)
    if not summary:
        sys.exit(0)

    trigger = data.get("trigger", "auto")
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    session_id = data.get("session_id", "unknown")

    content = (
        f"<!-- auto-generated by post-compact-capture.py — do not edit -->\n"
        f"# Last Compaction Summary\n\n"
        f"**Captured:** {timestamp}  \n"
        f"**Trigger:** {trigger}  \n"
        f"**Session:** {session_id}\n\n"
        f"---\n\n"
        f"{summary.strip()}\n"
    )

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(content)

    sys.exit(0)


if __name__ == "__main__":
    main()
