[CmdletBinding()]
param()

# Output path overrides for test isolation
$OutputPath = if ($env:COMPACT_OUTPUT_PATH) { $env:COMPACT_OUTPUT_PATH } else { Join-Path $HOME ".claude/last-compact-summary.md" }
$BackupPath = if ($env:COMPACT_BACKUP_PATH) { $env:COMPACT_BACKUP_PATH } else { Join-Path $HOME ".claude/last-compact-summary.bak.md" }

$StdinContent = [Console]::In.ReadToEnd()

# Parse JSON — fail open on malformed input
$Data = $null
try { $Data = $StdinContent | ConvertFrom-Json } catch { exit 0 }
if (-not $Data) { exit 0 }

$TranscriptPath = $Data.transcript_path
$Trigger        = if ($Data.trigger)    { $Data.trigger }    else { 'auto' }
$SessionId      = if ($Data.session_id) { $Data.session_id } else { 'unknown' }

# Validate transcript_path
if (-not $TranscriptPath) { exit 0 }
if (-not [System.IO.Path]::IsPathRooted($TranscriptPath)) { exit 0 }
if (-not (Test-Path $TranscriptPath)) { exit 0 }

# Read JSONL transcript — returns empty array for an empty file, which is fine
$Lines = @(Get-Content -Path $TranscriptPath -Encoding UTF8)

# ── Step 1: find last compact_boundary UUID ───────────────────────────────────
$BoundaryUuid = $null
foreach ($Line in $Lines) {
    if ($Line -match '"subtype"\s*:\s*"compact_boundary"') {
        try {
            $Obj = $Line | ConvertFrom-Json
            if ($Obj.uuid) { $BoundaryUuid = $Obj.uuid }
        } catch {}
    }
}

# ── Step 2 (primary): user entry whose parentUuid matches the boundary ─────────
$Summary       = $null
$FailureReason = $null

if ($BoundaryUuid) {
    # Literal match — escape the UUID so regex-special chars in UUIDs don't matter
    $UuidPattern = [regex]::Escape('"parentUuid":"' + $BoundaryUuid + '"')
    foreach ($Line in $Lines) {
        if ($Line -match $UuidPattern) {
            try {
                $Obj = $Line | ConvertFrom-Json
                $Msg = $Obj.message
                if ($Msg) {
                    if ($Msg.content -is [string] -and $Msg.content) {
                        $Summary = $Msg.content
                        break
                    }
                    if ($Msg.content -is [array]) {
                        $TextBlock = $Msg.content | Where-Object { $_.type -eq 'text' } | Select-Object -First 1
                        if ($TextBlock -and $TextBlock.text) { $Summary = $TextBlock.text; break }
                    }
                }
            } catch {}
        }
    }
}

# ── Step 3 (fallback): last assistant message ──────────────────────────────────
if (-not $Summary) {
    $Fallback = $null
    foreach ($Line in $Lines) {
        try {
            $Obj = $Line | ConvertFrom-Json
            if ($Obj.message -and $Obj.message.role -eq 'assistant') {
                $MsgContent = $Obj.message.content
                if ($MsgContent -is [string] -and $MsgContent) {
                    $Fallback = $MsgContent
                } elseif ($MsgContent -is [array]) {
                    $TextBlock = $MsgContent | Where-Object { $_.type -eq 'text' } | Select-Object -First 1
                    if ($TextBlock -and $TextBlock.text) { $Fallback = $TextBlock.text }
                }
            }
        } catch {}
    }

    if ($Fallback) {
        $Summary       = $Fallback
        $FailureReason = "primary extraction failed — using last assistant message as fallback"
    } else {
        $FailureReason = "no compact_boundary found and no assistant content in transcript"
    }
}

# ── Rotate existing summary before writing ─────────────────────────────────────
if (Test-Path $OutputPath) { Copy-Item -Path $OutputPath -Destination $BackupPath -Force }

# ── Write output ───────────────────────────────────────────────────────────────
$Timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm UTC")
$OutDir = Split-Path $OutputPath -Parent
if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Path $OutDir -Force | Out-Null }

if (-not $Summary) {
    $FileContent = @"
<!-- auto-generated by post-compact-capture.ps1 — do not edit -->
# Last Compaction Summary

**Captured:** $Timestamp
**Trigger:** $Trigger
**Session:** $SessionId

---

[EXTRACTION FAILED: $FailureReason]

The previous session's context could not be recovered from this compaction.
Start fresh or check ~/.claude/last-compact-summary.bak.md for the prior summary.
"@
} else {
    $FileContent = @"
<!-- auto-generated by post-compact-capture.ps1 — do not edit -->
# Last Compaction Summary

**Captured:** $Timestamp
**Trigger:** $Trigger
**Session:** $SessionId

---

$Summary
"@
}

Set-Content -Path $OutputPath -Value $FileContent -Encoding UTF8
