#!/usr/bin/env bash
# PostCompact hook — extracts compaction summary from transcript and saves it.
#
# Input (stdin):  {"transcript_path":"/abs/path","trigger":"auto","session_id":"..."}
# Output:         writes ~/.claude/last-compact-summary.md
#
# Resilience:
#   - Fallback extraction if primary (parentUuid match) finds nothing
#   - Rotates existing summary to .bak.md before overwriting
#   - Writes a diagnostic file on failure so the next session knows not to trust it
#
# Security: transcript_path validated as absolute before use; no eval or shell interpolation.

set -euo pipefail

# Allow tests to override output paths via env vars so the test suite never
# touches the user's real ~/.claude/ files.
OUTPUT_PATH="${COMPACT_OUTPUT_PATH:-${HOME}/.claude/last-compact-summary.md}"
BACKUP_PATH="${COMPACT_BACKUP_PATH:-${HOME}/.claude/last-compact-summary.bak.md}"

INPUT=$(cat)

# Extract fields; || true prevents grep exit-1 from aborting under set -e
TRANSCRIPT_PATH=$(printf '%s' "$INPUT" | grep -oE '"transcript_path":"[^"]*"' | head -1 | cut -d'"' -f4 || true)
TRIGGER=$(printf '%s' "$INPUT" | grep -oE '"trigger":"[^"]*"' | head -1 | cut -d'"' -f4 || true)
SESSION_ID=$(printf '%s' "$INPUT" | grep -oE '"session_id":"[^"]*"' | head -1 | cut -d'"' -f4 || true)

[[ -z "$TRANSCRIPT_PATH" ]] && exit 0
# Reject relative paths (path traversal guard)
[[ "${TRANSCRIPT_PATH:0:1}" != "/" ]] && exit 0
[[ ! -f "$TRANSCRIPT_PATH" ]] && exit 0

[[ -z "$TRIGGER" ]]    && TRIGGER="auto"
[[ -z "$SESSION_ID" ]] && SESSION_ID="unknown"

# ── extraction ────────────────────────────────────────────────────────────────

SUMMARY=""
FAILURE_REASON=""
FALLBACK_USED=0

# Step 1: find the compact_boundary UUID (last occurrence wins)
BOUNDARY_UUID=""
while IFS= read -r LINE || [[ -n "$LINE" ]]; do
  if printf '%s' "$LINE" | grep -qF '"subtype":"compact_boundary"'; then
    BOUNDARY_UUID=$(printf '%s' "$LINE" | grep -oE '"uuid":"[^"]*"' | head -1 | cut -d'"' -f4 || true)
  fi
done < "$TRANSCRIPT_PATH"

# Step 2 (primary): find user entry whose parentUuid matches the boundary
if [[ -n "$BOUNDARY_UUID" ]]; then
  while IFS= read -r LINE || [[ -n "$LINE" ]]; do
    if printf '%s' "$LINE" | grep -qF "\"parentUuid\":\"${BOUNDARY_UUID}\""; then
      # Extract JSON string value — handles escape sequences via [^"\\]*(\\.[^"\\]*)*
      SUMMARY=$(printf '%s' "$LINE" | grep -oE '"content":"([^"\\]|\\.)*"' | head -1 \
        | sed 's/^"content":"//; s/"$//' \
        | sed 's/\\n/\n/g; s/\\t/\t/g; s/\\"/"/g; s/\\\\/\\/g' \
        || true)
      if [[ -z "$SUMMARY" ]]; then
        # Array content block: {"type":"text","text":"..."}
        SUMMARY=$(printf '%s' "$LINE" | grep -oE '"text":"([^"\\]|\\.)*"' | head -1 \
          | sed 's/^"text":"//; s/"$//' \
          | sed 's/\\n/\n/g; s/\\t/\t/g; s/\\"/"/g; s/\\\\/\\/g' \
          || true)
      fi
      break
    fi
  done < "$TRANSCRIPT_PATH"
fi

# Step 3 (fallback): scan for the last substantial assistant message
if [[ -z "$SUMMARY" ]]; then
  FALLBACK=""
  while IFS= read -r LINE || [[ -n "$LINE" ]]; do
    if printf '%s' "$LINE" | grep -qF '"role":"assistant"'; then
      CANDIDATE=$(printf '%s' "$LINE" | grep -oE '"content":"([^"\\]|\\.)*"' | head -1 \
        | sed 's/^"content":"//; s/"$//' \
        | sed 's/\\n/\n/g; s/\\t/\t/g; s/\\"/"/g; s/\\\\/\\/g' \
        || true)
      [[ -n "$CANDIDATE" ]] && FALLBACK="$CANDIDATE"
    fi
  done < "$TRANSCRIPT_PATH"

  if [[ -n "$FALLBACK" ]]; then
    SUMMARY="$FALLBACK"
    FAILURE_REASON="primary extraction failed — using last assistant message as fallback"
    FALLBACK_USED=1
  else
    FAILURE_REASON="no compact_boundary found and no assistant content in transcript"
  fi
fi

# ── rotate existing summary before writing ────────────────────────────────────
if [[ -f "$OUTPUT_PATH" ]]; then
  cp "$OUTPUT_PATH" "$BACKUP_PATH"
fi

# ── write output ──────────────────────────────────────────────────────────────
TIMESTAMP=$(date -u "+%Y-%m-%d %H:%M UTC" 2>/dev/null || date "+%Y-%m-%d %H:%M UTC")
mkdir -p "$(dirname "$OUTPUT_PATH")"

if [[ -z "$SUMMARY" ]]; then
  # Write diagnostic so the next session knows the summary is not trustworthy
  cat > "$OUTPUT_PATH" << EOF
<!-- auto-generated by post-compact-capture.sh — do not edit -->
# Last Compaction Summary

**Captured:** ${TIMESTAMP}
**Trigger:** ${TRIGGER}
**Session:** ${SESSION_ID}

---

[EXTRACTION FAILED: ${FAILURE_REASON}]

The previous session's context could not be recovered from this compaction.
Start fresh or check ~/.claude/last-compact-summary.bak.md for the prior summary.
EOF
else
  # When fallback was used, prepend a note so the next session knows the source.
  _FALLBACK_NOTE=""
  [[ $FALLBACK_USED -eq 1 ]] && _FALLBACK_NOTE=$'<!-- Note: primary extraction failed — using last assistant message as fallback -->\n\n'
  cat > "$OUTPUT_PATH" << EOF
<!-- auto-generated by post-compact-capture.sh — do not edit -->
# Last Compaction Summary

**Captured:** ${TIMESTAMP}
**Trigger:** ${TRIGGER}
**Session:** ${SESSION_ID}

---

${_FALLBACK_NOTE}${SUMMARY}
EOF
fi
